#!/bin/bash

launchctl load /Library/LaunchDaemons/com.trmacs.pinotify.plist
# loads the just installed launchdaemon.  If previously loaded, was unloaded in Preflight.
vers="pinotify_postflight_v.0.3"

echo "$vers"
echo "loading Private Eyes Launchd's; pinotify, pi-checkin and pi-schedule "
launchctl load -w /Library/LaunchDaemons/com.trmacs.pinotify.plist
launchctl load -w /Library/LaunchDaemons/com.trmacs.pi-schedule.plist
launchctl load -w /Library/LaunchDaemons/com.trmacs.pi-checkin.plist

sleep 2

#running pi-schedule again to set IsWeekday
/Library/Scripts/trmacs/pi-schedule.sh

# Manually adding the necessary framework for settings.plist
/usr/libexec/PlistBuddy -c "Add :hash string 00000000000000000000000000000000" /Library/Scripts/trmacs/settings.plist


echo "done"
echo "exiting"

exit 0